[package]
name = "aidulc"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
toml = "0.8"
reqwest = { version = "0.12", features = ["json", "blocking"], default-features = false }
win32job = "2.0"
keyring = { version = "3", features = ["windows-native"] }
sha2 = "0.10"
rfd = "0.15"
base64 = "0.22"

[profile.release]
opt-level = 2
